Repository fe13-part3-team1/taskify, pull requests merged in 2025-04, with the labels that each got.

#107 Refactor : replace mock data with API
  app/(dashboard)/dashboard/[dashboardId]/edit/BackLink.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/DashboardTitleSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/InvitationListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/InviteModal.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/MemberListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/data.ts
  app/(dashboard)/dashboard/[dashboardId]/edit/page.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/types.ts
  app/(dashboard)/mydashboard/CreateDashboardModal.tsx
  app/(dashboard)/mydashboard/InvitedDashboardList.tsx
  app/(dashboard)/mydashboard/InvitedSection.tsx
  app/(dashboard)/mydashboard/MyDashboardListItem.tsx
  app/(dashboard)/mydashboard/MyDashboardSection.tsx
  app/(dashboard)/mydashboard/data.ts
  app/(dashboard)/mydashboard/page.tsx
  app/(dashboard)/mydashboard/types.ts
  components/DashboardColorIcon/DashboardColorIcon.tsx
  components/Pagination/PaginationItems.tsx
  components/layout/Header/InvitationButton.tsx
  components/layout/SideNav/DashboardListItem.tsx
  components/layout/SideNav/index.tsx
  components/layout/SideNav/sideNavItems.tsx
  components/layout/SideNav/useSideNavDashboards.tsx
  mocks/dashboards.ts
Labels: Refactor

#109 Fix : mypage, login
  app/(auth)/login/LoginForm.tsx
  app/(dashboard)/mypage/ChangePasswordForm.tsx
  app/(dashboard)/mypage/ProfileEditForm.tsx
  app/(dashboard)/mypage/page.tsx
Labels: Fix

#110 Fix : Header
  components/layout/Header/DashboardHeader.tsx
  components/layout/Header/Navigation.tsx
  components/layout/Header/UserHeader.tsx
Labels: Fix

#112 Feat : 회원 가입 시 로그인 기능 추가
  components/SignupForm/SignupForm.tsx
  components/SignupForm/action.ts
  components/SignupForm/login.ts
Labels: Feat

#114 Fix : Pagination error
  app/(dashboard)/mydashboard/data.ts
  components/Pagination/PaginationItems.tsx
  components/Pagination/usePagination.ts
  components/layout/SideNav/sideNavItems.tsx
  components/layout/SideNav/useSideNavDashboards.tsx
Labels: Fix

#113 Feat : dashboard card drag n drop
  components/Dashboard/DashboardCard/DashboardCard.tsx
  components/Dashboard/DashboardCard/SortableCard.tsx
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/Dashboard/DashboardColumn/db.ts
  package-lock.json
  package.json
Labels: Feat

#115 Feat : 409 error
  components/SignupForm/PasswordToggleBtn.tsx
  components/SignupForm/SignupForm.tsx
  components/SignupForm/action.ts
  components/SignupForm/useSignupForm.ts
  lib/api.ts
Labels: Feat

#117 Style : Responsive layout (mydashboard, dashboard-edit)
  app/(dashboard)/dashboard/[dashboardId]/edit/BackLink.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/DashboardTitleSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/InvitationListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/InviteModal.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/MemberListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/page.tsx
  app/(dashboard)/mydashboard/CreateDashboardModal.tsx
  app/(dashboard)/mydashboard/InvitedDashboardList.tsx
  app/(dashboard)/mydashboard/MyDashboardListItem.tsx
  app/(dashboard)/mydashboard/MyDashboardSection.tsx
  components/common/Button/style.ts
Labels: Style

#106 Feat : Redirection
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  constants/routes/index.ts
  middleware.ts
Labels: Feat

#118 Feat : update todo modal & card detail modal api
  components/Dashboard/DashboardCard/DashboardCard.tsx
  components/Dashboard/DashboardCard/SortableCard.tsx
  components/Dashboard/DashboardCard/action.ts
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/Tag/Tag.tsx
  components/common/Modal/index.tsx
  components/compound/modal/ColumnDetailModal.tsx
  components/compound/modal/types.ts
Labels: Feat

#119 Feat : dashboardId page
  app/(dashboard)/dashboard/[dashboardId]/layout.tsx
  components/ColumnModal/ColumnManagementModal.tsx
  components/Dashboard/DashboardColumn/ColumnSettingList.tsx
  components/DeleteColumnModal/DeleteColumnModal.tsx
  components/ToDoFormModal/ToDoFormModal.tsx
  components/ToDoFormModal/useToDoData.tsx
Labels: Feat

#122 Feat : login
  app/(auth)/login/LoginForm.tsx
Labels: Feat

#123 Fix : UserBadge 수정 & Mypage 수정
  components/UserBadge/UserBadge.tsx
  components/compound/upload/UploadImage.tsx
  components/layout/Header/DashboardHeader.tsx
  components/layout/Header/MemberBadgeList.tsx
Labels: Fix

#128 Feat : card useMemo
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/compound/modal/ColumnDetailModal.tsx
Labels: Feat, Style

#130 Feat : comment
  components/Comment/Comment.tsx
  components/compound/modal/ColumnDetailModal.tsx
Labels: Feat

#131 Feat: infinite scroll (mydashboard)
  app/(dashboard)/mydashboard/InvitedDashboardList.tsx
  app/(dashboard)/mydashboard/InvitedSection.tsx
  app/(dashboard)/mydashboard/data.ts
Labels: Feat

#138 fix: 첫 번째 고정요소가 있을 때 2번째 페이지가 늦게 생기는 에러 수정
  app/(dashboard)/mydashboard/MyDashboardSection.tsx
  components/Pagination/PaginationItems.tsx
  components/Pagination/usePagination.ts
Labels: Fix

#140 Style : SideNav, dashboard edit page UX
  app/(dashboard)/dashboard/[dashboardId]/edit/InvitationListSection .tsx
  components/layout/SideNav/index.tsx
Labels: Style

#142 Chore: 공백 오류 수정
  components/layout/SideNav/index.tsx
Labels: Chore

#144 Refactor
  app/(dashboard)/dashboard/[dashboardId]/layout.tsx
  app/(dashboard)/dashboard/[dashboardId]/page.tsx
  app/globals.css
  components/ColumnModal/ColumnManagementModal.tsx
  components/Comment/Comment.tsx
  components/Dashboard/AddColumnBtn.tsx
  components/Dashboard/DashboardCard/DashboardCard.tsx
  components/Dashboard/DashboardCard/SortableCard.tsx
  components/Dashboard/DashboardColumn/AddCardBtn.tsx
  components/Dashboard/DashboardColumn/ColumnSettingList.tsx
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/ToDoFormModal/ToDoFormModal.tsx
  components/ToDoFormModal/useToDoData.tsx
  components/common/Button/style.ts
  components/compound/modal/ColumnDetailModal.tsx
  utils/formatDateTime.ts
Labels: Refactor

#146 Refactor : instant card update
  components/ToDoFormModal/useToDoData.tsx
Labels: Refactor

#150 Refactor : useClickOutside
  hooks/useClickOutside.ts
Labels: Refactor

#153 Refactor: Globals.css - default font color
  app/(auth)/login/LoginForm.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/page.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/DeleteDashboardModal.tsx
  app/(dashboard)/mydashboard/InvitedSection.tsx
  app/(dashboard)/mydashboard/MyDashboardListItem.tsx
  app/(dashboard)/mydashboard/MyDashboardSection.tsx
  app/(dashboard)/mypage/ChangePasswordForm.tsx
  app/(dashboard)/mypage/ProfileEditForm.tsx
  app/globals.css
  app/not-found.tsx
  components/BackLink/BackLink.tsx
  components/ColumnModal/ColumnManagementModal.tsx
  components/Comment/Comment.tsx
  components/Dashboard/AddColumnBtn.tsx
  components/DeleteColumnModal/DeleteColumnModal.tsx
  components/Pagination/PaginationControls.tsx
  components/SignupForm/components/CheckBox.tsx
  components/SignupForm/components/SignupForm.tsx
  components/ToDoFormModal/DueDate.tsx
  components/ToDoFormModal/TagInput.tsx
  components/ToDoFormModal/ToDoFormModal.tsx
  components/common/Button/style.ts
  components/common/Input/index.tsx
  components/common/Modal/index.tsx
  components/common/Textarea/index.tsx
  components/compound/form/FormField.tsx
  components/compound/modal/ColumnDetailModal.tsx
Labels: Refactor

#152 Refactor : Login
  app/(auth)/login/LoginForm.tsx
  app/(auth)/login/page.tsx
  app/(auth)/login/useLoginForm.tsx
  components/LoginForm/PasswordToggle.tsx
  hooks/useToggle.ts
Labels: Refactor

#154 Refactor : mypage
  app/(dashboard)/mypage/ChangePasswordForm.tsx
  app/(dashboard)/mypage/ProfileEditForm.tsx
  app/(dashboard)/mypage/page.tsx
  app/(dashboard)/mypage/useChangePasswordForm.tsx
  app/(dashboard)/mypage/useProfileEditForm.tsx
Labels: Refactor

#155 Refactor : separate api client & server
  app/(dashboard)/mydashboard/CreateDashboardModal.tsx
  app/api/users/route.ts
  components/ColumnModal/ColumnManagementModal.tsx
  components/Comment/Comment.tsx
  components/Dashboard/DashboardCard/action.ts
  components/Dashboard/DashboardColumn/action.ts
  components/DeleteColumnModal/DeleteColumnModal.tsx
  components/SignupForm/utils/useSignupForm.ts
  components/ToDoFormModal/action.ts
  components/ToDoFormModal/useToDoData.tsx
  components/compound/modal/ColumnDetailModal.tsx
  components/layout/Header/DashboardHeader.tsx
  lib/apiClient.ts
  lib/apiServer.ts
  lib/createFetchOptions.ts
Labels: Refactor
