Repository fe13-part3-team1/taskify, pull requests merged in 2025-03, with the labels that each got.

#2 Style : globals css
  app/globals.css
  tailwind.config.js
Labels: Style

#11 Feature : Dropdown 컴포넌트 구현
  assets/icons/ArrowDropDown.tsx
  assets/icons/CheckIcon.tsx
  assets/icons/CloseIcon.tsx
  assets/icons/KebabVertIcon.tsx
  components/common/Dropdown/Input.tsx
  components/common/Dropdown/Item.tsx
  components/common/Dropdown/List.tsx
  components/common/Dropdown/Trigger.tsx
  components/common/Dropdown/index.tsx
  components/common/Dropdown/types.ts
  public/arrow_drop_down.svg
  public/check.svg
  public/close_small.svg
  public/kebab_more_vert.svg
Labels: Feat

#20 Feat : dashboard card
  assets/icons/UserIcon.tsx
  components/DashboardCard/DashboardCard.tsx
  components/UserBadge/UserBadge.tsx
  public/.gitkeep
  public/icons/date.svg
  public/icons/user.svg
Labels: Feat

#27 Feat : Modal
  components/common/Modal/index.tsx
  components/common/Modal/style.ts
Labels: Feat

#28 Feat : fetch api module
  lib/.gitkeep
  lib/api.ts
  utils/localstorage.ts
Labels: Feat

#30 Style : Login Page
  app/(auth)/layout.tsx
  app/(auth)/login/page.tsx
  public/logo.png
Labels: Style

#35 Style : global cursor style for Button
  app/globals.css
  components/common/Button/index.tsx
Labels: Style

#33 Feat : signup page
  app/(auth)/layout.tsx
  app/(auth)/signup/page.tsx
  components/SignupForm/CheckBox.tsx
  components/SignupForm/SignupForm.tsx
  components/SignupForm/action.ts
  components/SignupForm/useSignupForm.ts
  public/icons/check.svg
  public/icons/closeEye.svg
  public/icons/logo.svg
  public/icons/openEye.svg
  public/logo.png
  utils/authValidate.ts
Labels: Feat

#25 Feat : HeaderGuest + Fix: global.css @layer components
  app/globals.css
  assets/icons/Logo.tsx
  components/layout/Header/HeaderGuest.tsx
Labels: Feat

#39 Style : modal responsive css
  components/common/Modal/index.tsx
  components/common/Modal/style.ts
Labels: Style

#36 Fix : svg icon size
  assets/icons/ArrowDropDown.tsx
  assets/icons/CheckIcon.tsx
  assets/icons/CloseIcon.tsx
  assets/icons/KebabVertIcon.tsx
  components/common/Dropdown/Trigger.tsx
Labels: Fix

#42 Feat : SideNav component
  app/(dashboard)/layout.tsx
  assets/icons/AddBoxGrayIcon.tsx
  components/DashboardColorIcon/DashboardColorIcon.tsx
  components/layout/SideNav/AddDashboardButton.tsx
  components/layout/SideNav/DashboardListItem.tsx
  components/layout/SideNav/index.tsx
  mocks/dashboards.ts
  public/icons/addbox.svg
  public/icons/crown.svg
  public/logo-large.svg
Labels: Feat

#40 Feat : dashboard column
  assets/icons/Setting.tsx
  components/Dashboard/DashboardCard/DashboardCard.tsx
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/common/Button/style.ts
  public/icons/plus.svg
Labels: Feat

#45 Feat : to do form modal
  components/ColumnName/ColumnName.tsx
  components/ToDoFormModal/ToDoForm.tsx
  components/ToDoFormModal/ToDoFormModal.tsx
  components/common/Dropdown/Input.tsx
  components/common/Dropdown/Trigger.tsx
Labels: Feat

#47 Style : HeaderUser
  assets/icons/AddBoxGrayIcon.tsx
  assets/icons/Setting.tsx
  components/layout/Header/HeaderGuest.tsx
  components/layout/Header/HeaderUser.tsx
  components/layout/Header/MemberBadgeList.tsx
Labels: Style

#52 Feat : DashboardId Edit Page UI
  app/(dashboard)/dashboard/[id]/edit/BackLink.tsx
  app/(dashboard)/dashboard/[id]/edit/DashboardNameSection .tsx
  app/(dashboard)/dashboard/[id]/edit/InvitationListSection .tsx
  app/(dashboard)/dashboard/[id]/edit/InviteModal.tsx
  app/(dashboard)/dashboard/[id]/edit/MemberListSection .tsx
  app/(dashboard)/dashboard/[id]/edit/page.tsx
  assets/icons/ArrowLeft.tsx
Labels: Feat

#50 Feat : Mydashboard Page UI
  app/(dashboard)/layout.tsx
  app/(dashboard)/mydashboard/CreateDashboardModal.tsx
  app/(dashboard)/mydashboard/InvitedDashboardList.tsx
  app/(dashboard)/mydashboard/InvitedSection.tsx
  app/(dashboard)/mydashboard/MyDashboardSection.tsx
  app/(dashboard)/mydashboard/invitations.ts
  app/(dashboard)/mydashboard/page.tsx
  components/DashboardColorIcon/DashboardColorIcon.tsx
  components/common/Button/index.tsx
  mocks/invitations.ts
  public/icons/search.svg
  public/invite.svg
Labels: Feat

#48 Feat : dashboard id page
  app/(dashboard)/dashboard/[dashboardId]/edit/BackLink.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/DashboardNameSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/InvitationListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/InviteModal.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/MemberListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/page.tsx
  app/(dashboard)/dashboard/[dashboardId]/page.tsx
  app/(dashboard)/dashboard/[id]/page.tsx
  components/Dashboard/DashboardCard/DashboardCard.tsx
  components/Dashboard/DashboardCard/action.ts
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/Dashboard/DashboardColumn/action.ts
  components/UserBadge/UserBadge.tsx
  components/common/Button/style.ts
Labels: Feat

#53 Style: mypage
  app/(dashboard)/mypage/ChangePasswordForm.tsx
  app/(dashboard)/mypage/ProfileEditForm.tsx
  app/(dashboard)/mypage/page.tsx
  components/compound/upload/UploadImage.tsx
Labels: Style

#56 Fix : auth layout svgr -> Image
  app/(auth)/layout.tsx
Labels: Fix

#61 Feat : Save user information
  app/(auth)/login/LoginForm.tsx
  app/api/auth/login/route.ts
Labels: Feat

#62 Feat : tag component
  app/(dashboard)/dashboard/[dashboardId]/page.tsx
  components/Dashboard/ColorPalette.tsx
  components/Tag/Tag.tsx
  components/ToDoFormModal/TagInput.tsx
  components/ToDoFormModal/ToDoForm.tsx
  public/icons/whiteCheck.svg
  utils/separateTagColor.ts
Labels: Feat

#66 Style: Button Component
  components/common/Button/index.tsx
Labels: Style

#65 Feature - Apply header
  app/(dashboard)/dashboard/[dashboardId]/layout.tsx
  app/(dashboard)/layout.tsx
  app/(dashboard)/mydashboard/layout.tsx
  app/(dashboard)/mypage/layout.tsx
  app/page.tsx
  components/layout/Header/DashboardHeader.tsx
  components/layout/Header/GuestHeader.tsx
  components/layout/Header/HeaderUser.tsx
  components/layout/Header/UserHeader.tsx
  components/layout/Header/index.tsx
Labels: Feat

#69 Feat : useBlockScroll
  app/(dashboard)/dashboard/[dashboardId]/page.tsx
  components/common/Modal/index.tsx
  hooks/.gitkeep
  hooks/useBlockScroll.ts
Labels: Feat

#74 Refactor : Define api constants
  constants/api/external.ts
  constants/api/internal.ts
Labels: Refactor

#71 Feat : create to do card
  components/Dashboard/DashboardColumn/AddCardBtn.tsx
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/ToDoFormModal/DueDate.tsx
  components/ToDoFormModal/TagInput.tsx
  components/ToDoFormModal/ToDoForm.tsx
  components/ToDoFormModal/ToDoFormModal.tsx
  components/ToDoFormModal/action.ts
  components/ToDoFormModal/useToDoData.tsx
  package-lock.json
  package.json
Labels: Feat

#73 Feat: Mydashboard Page
  app/(dashboard)/mydashboard/InvitedDashboardList.tsx
  app/(dashboard)/mydashboard/InvitedSection.tsx
  app/(dashboard)/mydashboard/MyDashboardListItem.tsx
  app/(dashboard)/mydashboard/MyDashboardSection.tsx
  app/(dashboard)/mydashboard/page.tsx
  public/icons/arrowRight.svg
Labels: Feat

#76 Feat : Mypage
  app/(dashboard)/mypage/ChangePasswordForm.tsx
  app/(dashboard)/mypage/ProfileEditForm.tsx
  app/(dashboard)/mypage/page.tsx
Labels: Feat

#77 Feat/dashboard edit page
  app/(dashboard)/dashboard/[dashboardId]/edit/DashboardNameSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/DashboardTitleSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/InvitationListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/MemberListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/page.tsx
  assets/icons/AddBoxIcon.tsx
  components/DashboardColorIcon/DashboardColorIcon.tsx
  components/layout/Header/DashboardHeader.tsx
  components/layout/SideNav/AddDashboardButton.tsx
  public/icons/addbox.svg
Labels: Feat

#78 Feat : Header
  components/layout/Header/DashboardHeader.tsx
  components/layout/Header/InvitationButton.tsx
  components/layout/Header/UserHeader.tsx
  components/layout/Header/UserMenu.tsx
Labels: Feat

#84 Fix : add box icon
  components/layout/Header/InvitationButton.tsx
Labels: Fix

#79 Feat : create todo modal imageUrl & validate
  components/Dashboard/DashboardColumn/AddCardBtn.tsx
  components/ToDoFormModal/ToDoFormModal.tsx
  components/ToDoFormModal/action.ts
  components/ToDoFormModal/useToDoData.tsx
  components/common/Modal/index.tsx
  components/compound/upload/UploadImage.tsx
  constants/image/defaultCardImage.ts
  next.config.ts
  public/icons/pencil.svg
  utils/checkAllFormComplete.ts
  utils/formatDateTime.ts
Labels: Feat

#82 Feat : Logout
  app/api/auth/logout/route.ts
  components/layout/Header/UserMenu.tsx
  constants/api/internal.ts
  constants/routes/index.ts
Labels: Feat

#83 Fix : Login
  app/(auth)/layout.tsx
  app/(auth)/login/LoginForm.tsx
Labels: Fix

#86 Feat : column delete modal
  app/api/auth/logout/route.ts
  assets/icons/Setting.tsx
  components/Dashboard/DashboardColumn/ColumnSettingList.tsx
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/DeleteColumnModal/DeleteColumnModal.tsx
  types/modalProps.ts
Labels: Feat

#85 Feat : useClickOutside
  components/common/Dropdown/index.tsx
  components/layout/Header/UserMenu.tsx
  hooks/useClickOutside.ts
Labels: Feat

#91 Feat : add column modal
  app/(dashboard)/dashboard/[dashboardId]/page.tsx
  components/ColumnModal/ColumnManagementModal.tsx
  components/Dashboard/AddColumnBtn.tsx
  components/Dashboard/DashboardColumn/action.ts
  components/Dashboard/useDashboardParamsId.tsx
  components/DeleteColumnModal/DeleteColumnModal.tsx
  components/ToDoFormModal/ToDoFormModal.tsx
  components/common/Modal/index.tsx
Labels: Feat

#94 Feat : dashboard card
  app/(dashboard)/dashboard/[dashboardId]/layout.tsx
  app/(dashboard)/dashboard/[dashboardId]/page.tsx
  components/Dashboard/DashboardCard/DashboardCard.tsx
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  utils/formatDateTime.ts
Labels: Feat

#90 Feat: Pagination
  app/(dashboard)/dashboard/[dashboardId]/edit/BackLink.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/InvitationListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/MemberListSection .tsx
  app/(dashboard)/mydashboard/MyDashboardSection.tsx
  app/(dashboard)/mypage/page.tsx
  assets/icons/ArrowIcon.tsx
  components/Pagination/PaginationControls.tsx
  components/Pagination/PaginationItems.tsx
  components/Pagination/type.ts
  components/Pagination/usePagination.ts
  mocks/dashboards.ts
  mocks/invitations.ts
Labels: Feat

#88 Feat: Invite modal
  app/(dashboard)/dashboard/[dashboardId]/edit/InvitationListSection .tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/InviteModal.tsx
  app/(dashboard)/dashboard/[dashboardId]/edit/page.tsx
  components/layout/Header/DashboardHeader.tsx
  components/layout/Header/InvitationButton.tsx
Labels: Feat

#97 Feat : not found page
  app/not-found.tsx
  public/icons/people.svg
Labels: Feat

#98 Fix : Mypage
  app/(dashboard)/mypage/ProfileEditForm.tsx
  app/(dashboard)/mypage/page.tsx
  app/api/auth/logout/route.ts
  app/api/users/me/route.ts
  components/layout/Header/DashboardHeader.tsx
  components/layout/Header/GuestHeader.tsx
  components/layout/Header/UserHeader.tsx
  constants/api/internal.ts
Labels: Fix

#100 Feat : update column modal
  app/(dashboard)/dashboard/[dashboardId]/page.tsx
  components/ColumnModal/ColumnManagementModal.tsx
  components/Dashboard/DashboardColumn/ColumnSettingList.tsx
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/Dashboard/type.ts
Labels: Feat

#102 Feat : dashboard card update modal
  components/Dashboard/DashboardCard/DashboardCard.tsx
  components/Dashboard/DashboardCard/action.ts
  components/Dashboard/DashboardColumn/AddCardBtn.tsx
  components/Dashboard/DashboardColumn/DashboardColum.tsx
  components/Dashboard/DashboardColumn/action.ts
  components/ToDoFormModal/TagInput.tsx
  components/ToDoFormModal/ToDoFormModal.tsx
  components/ToDoFormModal/useToDoData.tsx
  components/common/Dropdown/Input.tsx
  components/common/Dropdown/Trigger.tsx
  components/common/Dropdown/index.tsx
  utils/formatDateTime.ts
Labels: Feat

#103 Feat: Pagination - SideNav
  components/Pagination/PaginationControls.tsx
  components/Pagination/type.ts
  components/layout/SideNav/index.tsx
Labels: Feat
